// Generated by CoffeeScript 1.12.7
(function() {
  var C, Chalice, Oracle, React, ReactDom;

  React = require('react');

  ReactDom = require('react-dom/server');

  Oracle = {
    summoner: React,
    name: 'React',
    isValidElement: React.isValidElement,
    Component: React.Component,
    createElement: React.createElement,
    conjurer: ReactDom.renderToString
  };

  Chalice = require('../src/chalice.coffee').Chalice;

  debugger;

  C = new Chalice(Oracle);

  module.exports = C.tags();

  module.exports.Chalice = Chalice;

}).call(this);
