// Generated by CoffeeScript 1.12.7
(function() {
  var C, Chalice, Mithril, Oracle;

  Mithril = require('mithril');

  Oracle = {
    summoner: Mithril,
    name: 'Mithril',
    createElement: Mithril
  };

  Chalice = require('../src/chalice.coffee').Chalice;

  debugger;

  C = new Chalice(Oracle);

  module.exports = C.tags();

  module.exports.Chalice = Chalice;

}).call(this);
