// Generated by CoffeeScript 1.12.7
(function() {
  var Halvalla, Mithril, Oracle;

  Mithril = require('mithril');

  Oracle = {
    summoner: Mithril,
    name: 'Mithril',
    createElement: Mithril,
    preInstantiate: true,
    getChildren: function(element) {
      return element.children;
    },
    getProp: function(element) {
      return element.attrs;
    },
    getName: function(element) {
      return element.tag;
    },
    propertyName: 'attrs',
    getName: function(element) {
      return element.tag;
    },
    trust: function(text) {
      return Mithril.trust(text);
    }
  };

  Halvalla = require('../lib/halvalla').Halvalla;

  module.exports = (new Halvalla(Oracle)).tags();

  module.exports.Halvalla = Halvalla;

}).call(this);
