// Generated by CoffeeScript 1.12.7
(function() {
  var C, Halvalla, Mithril, Oracle;

  require('mithril/test-utils/browserMock')(global);

  Mithril = require('mithril');

  Oracle = {
    summoner: Mithril,
    name: 'Mithril',
    createElement: Mithril,
    preInstantiate: true,
    getProp: function(element) {
      return element.attrs;
    },
    getName: function(element) {
      return element.tag;
    },
    trust: function(text) {
      return Mithril.trust(text);
    }
  };

  debugger;

  Halvalla = require('../src/halvalla.coffee').Halvalla;

  C = new Halvalla(Oracle);

  module.exports = C.tags();

  module.exports.Halvalla = Halvalla;

}).call(this);
