// Generated by CoffeeScript 1.12.7

/*
 * Halvalla -- bindings for element creation and expression via teact and teacup
 */


/*
 * The oracle, a globally supplied object to this module has this signature
Examples of oracle -- the default is to do Teacup to HTML
  ReactDom = require 'react-dom'
  Oracle =
    summoner: React
    name: 'React'
    isValidElement: React.isValidElement
    Component: React.Component
    createElement: React.createElement
    conjurer: ReactDom.renderToString
  Mithril = require 'mithril'
  Oracle =
    name: 'Mithril'
    isValidElement: (c)->c.view?
    createElement: Mithril
    Component: {}
 */

(function() {
  var GreatEmptiness, Halvalla, allTags, doctypes, dummyComponent, dummyElement, elements, escape, mergeElements, normalizeArray, propertyName, quote, ref, teacup,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    slice = [].slice,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ref = require('../src/html-tags'), doctypes = ref.doctypes, elements = ref.elements, normalizeArray = ref.normalizeArray, mergeElements = ref.mergeElements, allTags = ref.allTags, escape = ref.escape, quote = ref.quote;

  teacup = require('../src/teacup.coffee');

  propertyName = 'props';

  GreatEmptiness = null;

  dummyComponent = null;

  dummyElement = null;

  Halvalla = (function() {
    var oracle;

    oracle = null;

    function Halvalla(Oracle) {
      var Component, Element;
      if (Oracle == null) {
        Oracle = null;
      }
      this.renderable = bind(this.renderable, this);
      this.crel = bind(this.crel, this);
      this.crelVoid = bind(this.crelVoid, this);
      this.tag = bind(this.tag, this);
      this.ie = bind(this.ie, this);
      this.resetStack = bind(this.resetStack, this);
      this.mutator = bind(this.mutator, this);
      this.stack = null;
      GreatEmptiness = GreatEmptiness = (function() {
        function GreatEmptiness(instantiator, Oracle) {
          var Component, Element, defaultObject, key, ref1, value;
          if (Oracle == null) {
            Oracle = {};
          }
          defaultObject = {
            isValidElement: function(c) {
              return c.view != null;
            },
            name: 'great-emptiness',
            Component: Oracle.Component || (Component = (function() {
              function Component() {}

              return Component;

            })()),
            Element: Oracle.Element || (Element = (function() {
              function Element() {}

              return Element;

            })()),
            createElement: function() {
              var args;
              args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
              return (function(func, args, ctor) {
                ctor.prototype = func.prototype;
                var child = new ctor, result = func.apply(child, args);
                return Object(result) === result ? result : child;
              })(dummyElement, args, function(){});
            },
            summoner: null,
            getProp: function(element) {
              return element.attrs;
            },
            getName: function(element) {
              var ref1;
              return ((ref1 = element._Halvalla) != null ? ref1.tagName : void 0) || element.tag || element.type;
            },
            propertyName: 'attrs',
            conjurer: null
          };
          ref1 = Object.assign(defaultObject, Oracle);
          for (key in ref1) {
            value = ref1[key];
            GreatEmptiness.prototype[key] = value;
          }
          this.teacup = new teacup(instantiator, defaultObject);
          if (!this.conjurer) {
            this.conjurer = this.teacup.render.bind(this.teacup);
          }
          this;
        }

        return GreatEmptiness;

      })();
      oracle = new GreatEmptiness(this.instantiator, Oracle);
      propertyName = oracle.propertyName;
      dummyComponent = Component = (function(superClass) {
        extend(Component, superClass);

        function Component() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          Component.__super__.constructor.apply(this, args);
          this._Halvalla = {
            propertyName: propertyName
          };
          this;
        }

        Component.prototype.render = function() {};

        return Component;

      })(oracle.Component);
      dummyElement = Element = (function(superClass) {
        extend(Element, superClass);

        function Element() {
          var children1, properties, tagName;
          tagName = arguments[0], properties = arguments[1], children1 = 3 <= arguments.length ? slice.call(arguments, 2) : [];
          if (properties == null) {
            properties = {};
          }
          this.children = children1;
          Element.__super__.constructor.apply(this, [tagName, properties].concat(slice.call(this.children)));
          this[propertyName] = properties;
          if (this.children.length === 1) {
            this.children = this.children[0];
          }
          this._Halvalla = {
            tagName: tagName[0].toLowerCase() + tagName.slice(1),
            propertyName: propertyName,
            children: this[propertyName].children
          };
          this;
        }

        Element.prototype.view = function() {};

        return Element;

      })(oracle.Component);
    }

    Halvalla.prototype.mutator = function(tagName, destination, withThis) {
      var thing;
      if (withThis == null) {
        withThis = null;
      }
      allTags[tagName] = Halvalla.prototype[tagName] = (function() {
        return function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return destination.apply(null, [tagName].concat(slice.call(args)));
        };
      })();
      allTags[tagName].Halvalla = {
        tagName: tagName,
        boss: oracle.name
      };
      thing = allTags[tagName];
      return thing;
    };

    Halvalla.prototype.escape = escape;

    Halvalla.prototype.quote = quote;

    Halvalla.prototype.noDups = function(newElement) {
      var stack;
      if (!(stack = this.stack)) {
        return newElement;
      }
      if (!(stack.length > 0)) {
        stack.push(newElement);
      }
      if (newElement !== stack[stack.length - 1]) {
        stack.push(newElement);
      }
      return newElement;
    };

    Halvalla.prototype.resetStack = function(stack) {
      var previous;
      if (stack == null) {
        stack = null;
      }
      previous = this.stack;
      this.stack = stack;
      return previous;
    };

    Halvalla.prototype.pureComponent = function(contents) {
      return (function(_this) {
        return function() {
          var previous, result, stackHad;
          previous = _this.resetStack([]);
          result = contents.apply(_this, arguments);
          stackHad = _this.resetStack(previous);
          return stackHad;
        };
      })(this);
    };

    Halvalla.prototype.raw = function(text) {
      var el;
      if (!text.toString) {
        throw new Error("raw allows text only: expected a string");
      }
      if (oracle.trust) {
        el = oracle.trust(text);
      } else {
        el = oracle.createElement('text', {
          dangerouslySetInnerHTML: {
            __html: text.toString()
          }
        });
      }
      return this.noDups(el);
    };

    Halvalla.prototype.doctype = function(type) {
      if (type == null) {
        type = 5;
      }
      return this.raw(doctypes[type]);
    };

    Halvalla.prototype.ie = function(condition, contents) {
      return this.crel('ie', {
        condition: condition
      }, contents);
    };

    Halvalla.prototype.tag = function() {
      var args, attrs, children, contents, el, ref1, tagName;
      tagName = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (!((tagName != null) && 'string' === typeof tagName)) {
        throw new Error("HTML tag type is invalid: expected a string but got " + (typeof (tagName != null)));
      }
      ref1 = this.normalizeArgs(args), attrs = ref1.attrs, contents = ref1.contents;
      children = contents;
      el = oracle.createElement(tagName, attrs, children);
      return allTags[tagName] = Halvalla.prototype[tagName] = el;
    };

    Halvalla.prototype.bless = function(component, itsName) {
      var creator, name;
      if (itsName == null) {
        itsName = null;
      }
      if (component.__esModule && component["default"]) {
        component = component["default"];
      }
      name = itsName || component.name;
      creator = (function(_this) {
        return function() {
          var args, name, y;
          name = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
          y = oracle.createElement.apply(oracle, [component].concat(slice.call(args)));
          return y;
        };
      })(this);
      return this.mutator(name, creator, component);
    };

    Halvalla.prototype.renderContents = function() {
      var contents, ref1, rest;
      contents = arguments[0], rest = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (contents == null) {
        return;
      }
      if (typeof contents === 'function') {
        contents = contents.apply(this, rest);
      }
      if (typeof contents === 'number') {
        return this.noDups(contents);
      }
      if (typeof contents === 'string') {
        return this.noDups(contents);
      }
      if (contents.length > 0) {
        (ref1 = this.stack).push.apply(ref1, contents);
      }
    };

    Halvalla.prototype.component = function(func) {
      return (function(_this) {
        return function() {
          var args, attrs, contents, ref1, renderContents, selector;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          ref1 = _this.normalizeArgs(args), selector = ref1.selector, attrs = ref1.attrs, contents = ref1.contents;
          renderContents = function() {
            var args;
            args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
            args.unshift(contents);
            return _this.renderContents.apply(_this, args);
          };
          return func.apply(_this, [selector, attrs, renderContents]);
        };
      })(this);
    };

    Halvalla.prototype.crelVoid = function() {
      var args, attrs, contents, el, ref1, tagName;
      tagName = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      ref1 = this.normalizeArgs(args), attrs = ref1.attrs, contents = ref1.contents;
      if (contents.length > 0) {
        throw new Error("Element type is invalid: must not have content: " + tagName);
      }
      el = oracle.createElement(tagName, attrs, null);
      return this.noDups(el);
    };

    Halvalla.prototype.crel = function() {
      var args, attrs, children, contents, el, previous, ref1, stackHad, tagName;
      tagName = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if (tagName == null) {
        throw new Error("Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: " + tagName);
      }
      ref1 = this.normalizeArgs(args), attrs = ref1.attrs, contents = ref1.contents;
      previous = this.resetStack([]);
      this.march(contents);
      stackHad = this.resetStack(previous);
      children = stackHad;
      if (children != null ? children.splice : void 0) {
        el = oracle.createElement.apply(oracle, [tagName, attrs].concat(slice.call(children)));
      } else {
        el = oracle.createElement(tagName, attrs, children);
      }
      return this.noDups(el);
    };

    Halvalla.prototype.text = function(s) {
      if (!(s != null ? s.toString : void 0)) {
        return s;
      }
      return this.noDups(s.toString());
    };

    Halvalla.prototype.isSelector = function(string) {
      var ref1;
      return string.length > 1 && ((ref1 = string.charAt(0)) === '#' || ref1 === '.');
    };

    Halvalla.prototype.parseSelector = function(selector) {
      var classes, i, id, klass, len, ref1, ref2, token;
      id = null;
      classes = [];
      ref1 = selector.split('.');
      for (i = 0, len = ref1.length; i < len; i++) {
        token = ref1[i];
        token = token.trim();
        if (id) {
          classes.push(token);
        } else {
          ref2 = token.split('#'), klass = ref2[0], id = ref2[1];
          if (klass !== '') {
            classes.push(token);
          }
        }
      }
      return {
        id: id,
        classes: classes
      };
    };

    Halvalla.prototype.normalizeArgs = function(args) {
      var arg, attrs, classes, contents, dataAttrs, i, id, index, k, len, parsedSelector, selector, stuff, v;
      if (!args.length) {
        args = [args];
      }
      attrs = {};
      selector = null;
      contents = null;
      for (index = i = 0, len = args.length; i < len; index = ++i) {
        arg = args[index];
        if (arg != null) {
          switch (typeof arg) {
            case 'string':
              if (index === 0 && this.isSelector(arg)) {
                selector = arg;
                parsedSelector = this.parseSelector(arg);
              } else {
                contents = arg;
              }
              break;
            case 'number':
            case 'boolean':
              contents = arg;
              break;
            case 'function':
              if (oracle.preInstantiate) {
                stuff = this.render(arg);
                stuff = normalizeArray(stuff);
                contents = stuff;
              } else {
                contents = arg;
              }
              break;
            case 'object':
              if (arg.constructor === Object) {
                attrs = arg;
              }
              if (arg["default"] && arg.__esModule) {
                arg = arg["default"];
              }
              if (arg.constructor === Object && !oracle.isValidElement(arg)) {
                attrs = Object.keys(arg).reduce(function(clone, key) {
                  clone[key] = arg[key];
                  return clone;
                }, {});
              }
              if ((typeof arg.toString === "function" ? arg.toString() : void 0) !== '[object Object]') {
                contents = arg.toString();
              } else if (arg.length != null) {
                contents = arg;
              }
              break;
            default:
              contents = arg;
          }
        }
      }
      if (parsedSelector != null) {
        id = parsedSelector.id, classes = parsedSelector.classes;
        if (id != null) {
          attrs.id = id;
        }
        if (classes != null ? classes.length : void 0) {
          if (attrs["class"]) {
            classes.push(attrs["class"]);
          }
          attrs["class"] = classes.join(' ');
          if (attrs.className) {
            classes.push(attrs.className);
          }
          attrs.className = classes.join(' ');
        }
      }
      dataAttrs = attrs.data;
      if (typeof dataAttrs === 'object') {
        delete attrs.data;
        for (k in dataAttrs) {
          v = dataAttrs[k];
          attrs["data-" + k] = v;
        }
      }
      contents = normalizeArray(contents);
      return {
        attrs: attrs,
        contents: contents,
        selector: selector
      };
    };

    Halvalla.prototype.use = function(plugin) {
      return plugin(this);
    };

    Halvalla.prototype.renderable = function(stuff) {
      return (function(_this) {
        return function() {
          var args;
          args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
          return oracle.conjurer(_this.render.apply(_this, [stuff].concat(slice.call(args))));
        };
      })(this);
    };

    Halvalla.prototype.cede = function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return this.render.apply(this, args);
    };

    Halvalla.prototype.march = function(component) {
      var attrs, badDog, c, crell, i, l, len, result, tagConstructor, tagName, value;
      if (!(value = component != null ? component.toString() : void 0)) {
        return null;
      }
      switch (typeof component) {
        case 'function':
          l = this.stack.length;
          result = component();
          if (l === this.stack.length) {
            this.march(result);
          }
          return null;
        case 'string':
        case 'number':
          return this.noDups(component);
        case (Array.isArray(component)) && 'object':
          for (i = 0, len = component.length; i < len; i++) {
            c = component[i];
            this.march(c);
          }
          break;
        case (value !== '[object Object]') && 'object':
          return null;
        case 'object':
          try {
            tagName = oracle.getName(component);
            if ('function' === typeof tagName) {
              tagConstructor = tagName;
              tagName = tagConstructor.name;
              if (component.attrs) {
                attrs = component.attrs;
              } else {
                attrs = component.props;
              }
              if (tagName[0] !== tagName[0].toLowerCase()) {
                tagName = tagName[0].toLowerCase() + tagName.slice(1);
                if (!Halvalla.prototype[tagName]) {
                  Halvalla.prototype[tagName] = function() {
                    var args, component;
                    component = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
                    return this.crel.apply(this, [tagName, component].concat(slice.call(args)));
                  };
                }
                crell = this.crel(tagConstructor, attrs, component.props.children);
              } else {
                crell = this[tagName].apply(this, args);
              }
              return null;
            } else {
              return this.noDups(component);
            }
          } catch (error) {
            badDog = error;
            console.error(badDog);
            debugger;
            throw badDog;
          }
          break;
        default:
          debugger;
          throw new Error("bad component?", component);
          return;
      }
    };

    Halvalla.prototype.render = function() {
      var badDog, element, node, previous, rest, result, structure;
      node = arguments[0], rest = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      previous = this.resetStack([]);
      try {
        this.march(node.apply(null, rest));
      } catch (error) {
        badDog = error;
        debugger;
        throw badDog;
      }
      structure = this.resetStack(previous);
      if (previous !== null) {
        debugger;
      }
      this.resetStack();
      result = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = structure.length; i < len; i++) {
          element = structure[i];
          switch (typeof element) {
            case 'string':
            case 'number':
              element = this.crel('text', '', element);
          }
          results.push(oracle.conjurer(element));
        }
        return results;
      }).call(this);
      return result.join('');
    };

    Halvalla.prototype.tags = function() {
      var bound, boundMethodNames, fn, fn1, fn2, fn3, fn4, i, j, len, len1, len2, len3, len4, m, method, n, o, ref1, ref2, ref3, ref4, tagName;
      bound = {};
      bound.Oracle = oracle;
      bound.Component = dummyComponent;
      bound.Element = dummyElement;
      boundMethodNames = [].concat('bless cede component doctype escape ie normalizeArgs pureComponent raw render renderable tag text use'.split(' '), mergeElements('regular', 'obsolete', 'raw', 'void', 'obsolete_void', 'script', 'coffeescript', 'comment'));
      fn = (function(_this) {
        return function(method) {
          return allTags[method] = bound[method] = function() {
            var args;
            args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
            if (!_this[method]) {
              throw "no method named " + method + " in Halvalla";
            }
            return _this[method].apply(_this, args);
          };
        };
      })(this);
      for (i = 0, len = boundMethodNames.length; i < len; i++) {
        method = boundMethodNames[i];
        fn(method);
      }
      ref1 = mergeElements('regular', 'obsolete');
      fn1 = (function(_this) {
        return function(tagName) {
          return _this.mutator(tagName, _this.crel);
        };
      })(this);
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        tagName = ref1[j];
        fn1(tagName);
      }
      ref2 = mergeElements('raw');
      fn2 = (function(_this) {
        return function(tagName) {
          return _this.mutator(tagName, _this.crel);
        };
      })(this);
      for (m = 0, len2 = ref2.length; m < len2; m++) {
        tagName = ref2[m];
        fn2(tagName);
      }
      ref3 = mergeElements('script', 'coffeescript', 'comment');
      fn3 = (function(_this) {
        return function(tagName) {
          return _this.mutator(tagName, _this.crel);
        };
      })(this);
      for (n = 0, len3 = ref3.length; n < len3; n++) {
        tagName = ref3[n];
        fn3(tagName);
      }
      ref4 = mergeElements('void', 'obsolete_void');
      fn4 = (function(_this) {
        return function(tagName) {
          return _this.mutator(tagName, _this.crelVoid);
        };
      })(this);
      for (o = 0, len4 = ref4.length; o < len4; o++) {
        tagName = ref4[o];
        fn4(tagName);
      }
      return bound;
    };

    return Halvalla;

  })();

  if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    module.exports = new Halvalla().tags();
    module.exports.Halvalla = Halvalla;
  } else {
    window.Halvalla = new Halvalla().tags();
    window.Halvalla.Halvalla = Halvalla;
  }

}).call(this);
