// Generated by CoffeeScript 1.12.7
(function() {
  var C, Halvalla, Oracle, React, ReactDom;

  React = require('react');

  ReactDom = require('react-dom/server');

  debugger;

  Oracle = {
    summoner: React,
    name: 'React',
    isValidElement: React.isValidElement,
    Component: React.Component,
    createElement: React.createElement,
    createComponent: React.createComponent,
    conjurer: ReactDom.renderToStaticMarkup,
    preInstantiate: true,
    instantiateChildFunction: true,
    getProp: function(element) {
      return element.props;
    },
    propertyName: 'props',
    getName: function(element) {
      return element.tagName || element.type;
    }
  };

  Halvalla = require('../src/halvalla.coffee').Halvalla;

  C = new Halvalla(Oracle);

  module.exports = C.tags();

  module.exports.Halvalla = Halvalla;

}).call(this);
